;(function($,_,undefined){"use strict";ips.controller.register('invisionbyte.livemessenger.main',{_ajaxObj:null,initialize:function(){this.on(document,'mouseup',this.toggleChatFromDocument);this.on('click','.liveMessenger_chatHeader .ipsWidget_title, [data-action="toggleMessenger"]',this.toggleChat);this.on('click','[data-action="toggleMessengerBubble"]',this.toggleChatBubble);this.on('click','[data-action="openMessenger"] a',this.openMessenger);this.on('click','.liveMessenger_list:not(.liveMessenger_unread) .cMessage',this.readMessage);this.on('click','.liveMessenger_unread .cMessage',this.readMessageUnread);this.on('click','[data-action="backMessenger"]',this.back);this.on('submit','.messagesForm',this.quickReply);this.on(document,'addToMessengerFeed',this.addToMessengerFeed);$('.liveMessenger_list').on('scroll',this.scrollEvent.bind(this));this.on('click','.liveMessenger_scroller',this.scroll);this.on('input','.messagesForm #elInput_livemessenger_message',this.inputForm);this.on(document,'notificationCountUpdate',this.updateMessenger);this.on('menuItemSelected','#elMessengerSortByMenu',this.messengerSort);this.on('menuItemSelected','#elMessengerFilterMenu',this.messengerFilter);},updateMessenger:function(e,data){},messengerSort:function(e,data){if(data.originalEvent){data.originalEvent.preventDefault();}
var sort=data.selectedItemID;this._sort=sort;this.loadList();},messengerFilter:function(e,data){if(data.originalEvent){data.originalEvent.preventDefault();}
var filter=data.selectedItemID;this._filter=filter;this.loadList();},toggleChatFromDocument:function(e){if($('.liveMessenger_chat').hasClass('liveMessenger_opened')&&$(e.target).closest('.liveMessenger_chat').length===0){if($('.liveMessenger_list').hasClass('ipsLoading')){return;}
$('.liveMessenger_list').css({height:'auto'}).html('').removeClass('ipsLoading');if(this.scope.hasClass('bubbleChat')==true){$('.liveMessenger_chat').removeClass('liveMessenger_opened');$('.liveMessenger_chat_bubble').toggleClass('ipsHide');$('.liveMessenger_chatHeader').toggleClass('ipsHide');}
else{$('.liveMessenger_chat').removeClass('liveMessenger_opened');}
this.clear();}
return;if($('.liveMessenger_list').hasClass('ipsLoading')){return;}
e.stopPropagation();var item=$(e.currentTarget).parent().parent();if(item.children()&&$(item.children()[0]).hasClass('liveMessenger_chat_bubble')){if(item.hasClass('liveMessenger_opened')==true){$('.liveMessenger_chatHeader').addClass('ipsHide');}
item.removeClass('liveMessenger_chat');item.removeClass('liveMessenger_messageView');}
if(item.parent().find('.liveMessenger_chat_bubble')&&item.parent().find('.liveMessenger_chat_bubble').hasClass('ipsHide')){item.parent().find('.liveMessenger_chat_bubble').toggleClass('ipsHide');}
if(item.closest('.liveMessenger_chat_bubble').length==0){if(item.hasClass('liveMessenger_opened')){item.removeClass('liveMessenger_opened');}
else{item.addClass('liveMessenger_opened');}}
this.scope.find('.liveMessenger_chat').removeClass('hasUnread');if(item.hasClass('liveMessenger_opened')==true){$('.liveMessenger_list').html('').css({height:'200px'}).addClass('ipsLoading ipsLoading_mini');this.loadList();}
else{$('.liveMessenger_list').css({height:'auto'}).html('').removeClass('ipsLoading');this.clear();}},toggleChatBubble:function(e){e.stopPropagation();var item=$(e.currentTarget).parent();if(item.hasClass('liveMessenger_opened')){item.removeClass('liveMessenger_opened');$('.liveMessenger_chatHeader').addClass('ipsHide');}
else{item.addClass('liveMessenger_chat liveMessenger_opened');$('.liveMessenger_chatHeader').removeClass('ipsHide');}
if(item.hasClass('liveMessenger_opened')==true){$('.liveMessenger_list').html('').css({height:'200px'}).addClass('ipsLoading ipsLoading_mini');this.loadList();$('.liveMessenger_chat_bubble').toggleClass('ipsHide');}
else{$('.liveMessenger_list').css({height:'auto'}).html('').removeClass('ipsLoading');this.clear();}},inputForm:function(e){var button=this.scope.find('[type="submit"]');if(!$(e.currentTarget).val()){if(button.hasClass('ipsButton_disabled')==false){button.addClass('ipsButton_disabled');}}
else{button.removeClass('ipsButton_disabled');}},readMessageUnread:function(e){e.preventDefault();var item=$(e.currentTarget).parent().parent().parent();if(item.hasClass('liveMessenger_opened')){item.removeClass('liveMessenger_opened');}
else{item.addClass('liveMessenger_opened');}
$('.liveMessenger_list').html('').css({height:'200px'}).addClass('ipsLoading ipsLoading_mini');var messageid=$(e.currentTarget).attr('data-messageid');var url=ips.getSetting('baseURL')+'index.php?app=livemessenger&module=chat&controller=messenger&do=getConversation&mid='+messageid;var self=this;var ajaxObj=ips.getAjax();ajaxObj(url,{dataType:'json'}).done(function(returnedData){$('.liveMessenger_list').css({height:'auto'}).removeClass('ipsLoading').html(returnedData.data);self.scope.find('h3.ipsWidget_title').html(returnedData.title);self.scope.find('.liveMessenger_chat').addClass('liveMessenger_messageView');self.scope.find('[data-action="backMessenger"]').removeClass('ipsHide');self.scroll();self.readTopic(messageid);self.scope.find('.liveMessenger_unread').remove();}).fail(function(){});},readTopic:function(messageid){var ajaxObj=ips.getAjax();ajaxObj(ips.getSetting('baseURL')+'index.php?app=livemessenger&module=chat&controller=messenger&do=readConversation&mid='+messageid).done(function(returnedData){});},scrollEvent:function(e){if($(e.currentTarget).closest('.liveMessenger_chat').hasClass('liveMessenger_messageView')){var elem=this.scope.find('.liveMessenger_list [data-role="commentFeed"]');var scroller=this.scope.find('.liveMessenger_scroller');var destination=elem.position().top;var point=elem.height()-(elem.height()*20/100);if(destination>-point&&elem.height()>1000){scroller.addClass('liveMessenger_scrollerVisible');}else{scroller.removeClass('liveMessenger_scrollerVisible');}}},quickReply:function(e){e.preventDefault();e.stopPropagation();var form=this.scope.find('form.messagesForm');if(form.attr('data-noAjax')){return;}
if($(e.currentTarget).find('[type="submit"]').hasClass('ipsButton_disabled')==true){return;}
if(!$(e.currentTarget).find('[type="text"]').val()){return;}
var self=this;var feed=$(e.currentTarget).closest('[data-role="commentFeed"]');var replyArea=this.scope.find('.messagesForm');var submit=this.scope.find('.messagesForm [type="submit"]');var currentText=submit.text();submit.prop('disabled',true).text(ips.getString('livemessenger_sending'));ips.getAjax()(form.attr('action'),{data:form.serialize()+'&submitting=1',type:'post'}).done(function(response){self.trigger('addToMessengerFeed',{content:response.content});}).fail(function(){form.attr('data-noAjax','true');form.submit();}).always(function(){submit.prop('disabled',false).text(currentText);});},setup:function(e){},back:function(e){this.clear();$('.liveMessenger_list').html('').css({height:'200px'}).addClass('ipsLoading ipsLoading_mini');this.loadList();},readMessage:function(e){if($(e.currentTarget).closest('.liveMessenger_chat').hasClass('hasUnread')){return;}
var url=ips.getSetting('baseURL')+'index.php?app=livemessenger&module=chat&controller=messenger&do=getConversation&mid='+$(e.currentTarget).attr('data-messageid');var self=this;var ajaxObj=ips.getAjax();$('.liveMessenger_list').html('').css({height:'200px'}).addClass('ipsLoading ipsLoading_mini');ajaxObj(url,{dataType:'json'}).done(function(returnedData){$('.liveMessenger_list').css({height:'auto'}).removeClass('ipsLoading').html(returnedData.data);self.scope.find('h3.ipsWidget_title').html(returnedData.title);self.scope.find('.liveMessenger_chat').addClass('liveMessenger_messageView');self.scope.find('[data-action="backMessenger"]').removeClass('ipsHide');self.scope.find('[type="submit"]').addClass('ipsButton_disabled');self.scroll();}).fail(function(){});},openMessenger:function(e){},toggleChat:function(e){if($('.liveMessenger_list').hasClass('ipsLoading')){return;}
e.stopPropagation();var item=$(e.currentTarget).parent().parent();if(item.children()&&$(item.children()[0]).hasClass('liveMessenger_chat_bubble')){if(item.hasClass('liveMessenger_opened')==true){$('.liveMessenger_chatHeader').addClass('ipsHide');}
item.removeClass('liveMessenger_chat');item.removeClass('liveMessenger_messageView');}
if(item.parent().find('.liveMessenger_chat_bubble')&&item.parent().find('.liveMessenger_chat_bubble').hasClass('ipsHide')){item.parent().find('.liveMessenger_chat_bubble').toggleClass('ipsHide');}
if(item.closest('.liveMessenger_chat_bubble').length==0){if(item.hasClass('liveMessenger_opened')){item.removeClass('liveMessenger_opened');}
else{item.addClass('liveMessenger_opened');}}
this.scope.find('.liveMessenger_chat').removeClass('hasUnread');if(item.hasClass('liveMessenger_opened')==true){$('.liveMessenger_list').html('').css({height:'200px'}).addClass('ipsLoading ipsLoading_mini');this.loadList();}
else{$('.liveMessenger_list').css({height:'auto'}).html('').removeClass('ipsLoading');this.clear();}},loadList:function(e){var url=ips.getSetting('baseURL')+'index.php?app=livemessenger&module=chat&controller=messenger&do=getList';if(this._sort)url+="&sortBy="+this._sort;if(this._filter)url+="&filter="+this._filter;console.log(url);var self=this;var ajaxObj=ips.getAjax();ajaxObj(url,{dataType:'json'}).done(function(returnedData){if($('.liveMessenger_chat').hasClass('liveMessenger_opened')==true){$('.liveMessenger_list').css({height:'auto'}).removeClass('ipsLoading').html(returnedData.data);}
return;}).fail(function(){});},clear:function(e){this.scope.find('.liveMessenger_chat').removeClass('liveMessenger_messageView');this.scope.find('[data-action="backMessenger"]').addClass('ipsHide');this.scope.find('h3.ipsWidget_title').html(ips.getString('livemessenger_title_js'));this.scope.find('.liveMessenger_unread').remove();this.scope.find('.liveMessenger_chat').removeClass('hasUnread');},scroll:function(){var destination=this.scope.find('[data-role="commentFeed"]').height();$(".liveMessenger_list").animate({scrollTop:destination},500);},addToMessengerFeed:function(e,data){if(!data.content){return;}
var content=$('<div/>').append(data.content);this.scope.find('[data-role="commentFeed"]').append(content);ips.utils.anim.go('fadeInDown',content);this.scope.find('input#elInput_livemessenger_message').val('');this.scope.find('[type="submit"]').addClass('ipsButton_disabled');this.scroll();$(document).trigger('contentChange',[this.scope]);},});}(jQuery,_));;